/// Flutter icons Referral
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Referral
///      fonts:
///       - asset: fonts/Referral.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Referral {
  Referral._();

  static const _kFontFam = 'Referral';
  static const String? _kFontPkg = null;

  static const IconData news_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capital_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icons = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData how_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribe_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revenue_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invite_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capital_icon_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData complete_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connected_icon_copy = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewards_icons = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assets_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bind_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guides_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipod = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_set_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activate_icon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trade_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_icon = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer_19 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_mode_icon = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_icon__2_ = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdraw = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usdt = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team_subs = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct_sub = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subs_reward = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData todayusdt = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cumulusdt = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_team = IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xf555, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
