name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.45+45

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.2.1
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.1.0+1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  copy_with_extension: ^4.0.4
  dio: ^4.0.1
  equatable: ^2.0.3
  collection: ^1.16.0
  extended_image: ^6.2.1
  fl_chart: ^0.55.1
  flutter_bloc: ^8.0.1
  flutter_custom_clippers: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  auto_size_text: ^3.0.0
  flutter_inappwebview: ^5.4.3+7
  flutter_screenutil: ^5.3.1
  flutter_secure_storage: ^5.0.2
  flutter_form_builder: ^7.5.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  flutter_signin_button: ^2.0.0
  form_builder_validators: ^8.3.0
  form_builder_extra_fields: ^8.3.0
  google_sign_in: ^5.4.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.5
  http_parser: ^4.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.4.0
  line_icons: ^2.0.1
  loader_overlay: ^2.0.5+1
  logger: ^1.1.0
  lottie: ^1.2.2
  package_info_plus: ^1.4.3
  percent_indicator: ^4.0.0
  permission_handler: ^10.0.0
  retrofit: ^3.0.1+1
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  smooth_page_indicator: ^1.0.0+2
  synchronized: ^3.0.0
  table_calendar: ^3.0.7
  store_redirect: ^2.0.1
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  visibility_detector: ^0.3.3
  webview_flutter: ^3.0.4
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.1
  flutter_local_notifications: ^9.2.0
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  share_plus: ^6.2.0
  paged_vertical_calendar: ^1.1.5
  stream_transform: ^2.1.0
  crypto: ^3.0.2
  firebase_performance: ^0.9.0+6
  flutter_svg: ^1.1.6
  firebase_remote_config: ^3.0.6
  version: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.2.1
  build_runner: ^2.1.5
  copy_with_extension_gen: ^4.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.5
  hive_generator: ^1.1.0
  json_serializable: ^6.1.1
  intl_generator: ^0.3.0
  retrofit_generator: ^4.0.3


flutter_native_splash:
  image: "assets/images/native/logo_new.png"
  fullscreen: true
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans-Black.ttf
          weight: 900
        - asset: assets/fonts/EncodeSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSans-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/EncodeSans-Thin.ttf
          weight: 100
  assets:
    - assets/images/native/
    - assets/images/design/
    - assets/images/icons/
    - assets/images/svg/
    - assets/fonts/
