// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWJe57vSQHkQUG9i4ekERvu-hOussPfE',
    appId: '1:123907775175:android:5910b78872cec0990d7ce2',
    messagingSenderId: '123907775175',
    projectId: 'myairline-4ef5b',
    storageBucket: 'myairline-4ef5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboqPrX6-j9UAHD3_wF7lEo2JYll6N1RY',
    appId: '1:123907775175:ios:4ef6b02f82eeee9b0d7ce2',
    messagingSenderId: '123907775175',
    projectId: 'myairline-4ef5b',
    storageBucket: 'myairline-4ef5b.appspot.com',
    androidClientId: '123907775175-sblo9tqlicud2dodfvj5q03ffd21kfad.apps.googleusercontent.com',
    iosClientId: '123907775175-gr6cg40jdgiqta5rs9vcmsl8cvlfr77k.apps.googleusercontent.com',
    iosBundleId: 'com.myairline.mobileapp',
  );
}
